name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.7
        with:
          path: ./.env
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{ env.docker_version }}
